Repository fanpay/vynils_mobile, pull requests merged in 2023-11, with the labels that each got.

#52 HU02-PE2E consultar informacion detallada de un album
  app/build.gradle.kts
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/AlbumDetailFragmentTest.kt
Labels: HU02

#54 Se agregan pruebas con Espresso
  app/build.gradle.kts
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/AlbumActivityTest.kt.kt
  app/src/main/res/layout/album_item.xml
Labels: HU01

#55 [HU01] Actualización pruebas E2E
  app/build.gradle.kts
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/AlbumActivityTest.kt
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/Test1Vinyls.java
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/TestMainActivity.java
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/AlbumRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/AlbumViewModel.kt
  app/src/test/java/com/uniandes/vynilsmobile/AlbumViewModelTest.kt
Labels: HU01

#58 Micro-optimizaciones álbumes
  app/build.gradle.kts
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/AlbumActivityTest.kt
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/AlbumDetailFragmentTest.kt
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/TestMainActivity.java
  app/src/main/java/com/uniandes/vynilsmobile/data/service/RetrofitBroker.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumDetailFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CollectorFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CommentFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/MainActivity.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/adapters/AlbumsAdapter.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/AlbumDetailViewModel.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/CollectorViewModel.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/CommentViewModel.kt
  app/src/main/res/layout/album_detail_fragment.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/strings.xml
Labels: optimización

#63 [HU01] Actualizacion bd local room albumes
  app/build.gradle.kts
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/AlbumDetailFragmentTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uniandes/vynilsmobile/VinylsApplication.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/database/AlbumsDao.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/database/CollectorsDao.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/database/CommentsDao.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/database/VinylsDatabase.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/model/Album.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/model/Collector.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/model/Comment.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/AlbumRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/MainActivity.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/adapters/AlbumsAdapter.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/AlbumViewModel.kt
  app/src/main/res/drawable/ic_android_init_image.xml
  app/src/main/res/drawable/ic_android_not_data_found.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_foreground_2.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/uniandes/vynilsmobile/AlbumViewModelTest.kt
  build.gradle.kts
Labels: enhancement

#65 Feature/hu03 consultar listado artistas
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/ArtistActivityTest.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/ApiClient.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/uniandes/vynilsmobile/ArtistViewModelTest.kt
Labels: HU03

#66 Feature/hu04 detalle artistas
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/CollectorRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/ApiClient.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/CollectorApi.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/ArtistDetailFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/ArtistFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CollectorFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/MainActivity.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/adapters/CollectorsAdapter.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/CollectorViewModel.kt
  app/src/main/res/drawable/ic_baseline_artist_24.xml
  app/src/main/res/layout/artist_detail_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: HU04

#67 Se agregan pruebas e2e para el detalle de artista
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/ArtistDetailFragmentTest.kt
Labels: HU04

#68 [MICRO-OPTIMIZACION] Micro optimizaciones generales de la app
  app/build.gradle.kts
  app/src/main/java/com/uniandes/vynilsmobile/data/database/CollectorsDao.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/AlbumRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/ArtistRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/CollectorRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/CommentsRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/ArtistApi.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/CollectorApi.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/RetrofitBroker.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/ArtistDetailFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/ArtistFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CollectorFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CommentFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/adapters/CommentsAdapter.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/ArtistViewModel.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/CollectorViewModel.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/CommentViewModel.kt
  app/src/main/res/drawable-anydpi/ic_action_name.xml
  app/src/main/res/drawable-hdpi/ic_action_name.png
  app/src/main/res/drawable-mdpi/ic_action_name.png
  app/src/main/res/drawable-xhdpi/ic_action_name.png
  app/src/main/res/drawable-xxhdpi/ic_action_name.png
  app/src/main/res/drawable/ic_android_bug_crash_dead.xml
  app/src/main/res/drawable/ic_android_init_image.xml
  app/src/main/res/drawable/ic_android_not_data_found.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_foreground_2.xml
  app/src/main/res/layout/album_detail_fragment.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/artist_item.xml
  app/src/main/res/layout/collector_item.xml
  app/src/main/res/menu/layout_menu.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: optimización

#74 HU06-ConsultarDetalleColeccionista
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/CollectorDetailFragmentTest.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CollectorDetailFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CollectorFragment.kt
  app/src/main/res/layout/collector_detail_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: HU06

#75 [HU07] Funcionalidad para crear album
  app/build.gradle.kts
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/AlbumCreateFragmentTest.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/database/AlbumsDao.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/model/Album.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/AlbumRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/AlbumApi.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/RetrofitBroker.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumCreateFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumDetailFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/MainActivity.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/AlbumCreateViewModel.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/AlbumViewModel.kt
  app/src/main/res/drawable/ic_add_circle.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_detail_fragment.xml
  app/src/main/res/layout/album_fragment.xml
  app/src/main/res/layout/album_fragment_create.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/artist_detail_fragment.xml
  app/src/main/res/layout/artist_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: HU07

#76 [HU07]Se solucionan conflictos en el archivo String
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumCreateFragment.kt
  app/src/main/res/values/strings.xml
Labels: HU07

#77 [HU03] Consultar listado artistas más corrutinas room
  app/src/main/java/com/uniandes/vynilsmobile/data/database/ArtistsDao.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/database/VinylsDatabase.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/model/Artist.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/ArtistRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/ArtistFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CollectorDetailFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/adapters/ArtistsAdapter.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/ArtistViewModel.kt
  app/src/main/res/drawable/ic_add_circle.xml
  app/src/main/res/values/strings.xml
Labels: HU03

#78 [accessibility] Se crea rama para solucionar problemas de accesibilidad
  app/src/androidTest/java/com/uniandes/vynilsmobile/view/TestMainActivity.java
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/ArtistFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CollectorFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_fragment_create.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/artist_item.xml
  app/src/main/res/layout/collector_item.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#80 [HU13] Nueva funcionalidad para crear premios
  app/src/main/java/com/uniandes/vynilsmobile/data/database/PrizesDao.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/database/VinylsDatabase.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/model/Prize.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/PrizeRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/ApiClient.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/PrizeApi.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/RetrofitBroker.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CollectorFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/PrizeCreateFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/PrizeCreateViewModel.kt
  app/src/main/res/drawable/ic_prize_add_button.xml
  app/src/main/res/layout/collector_detail_fragment.xml
  app/src/main/res/layout/collector_fragment.xml
  app/src/main/res/layout/prize_create_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 3

#79 Se agrega botón y funcionalidad de crear comentario
  app/src/main/java/com/uniandes/vynilsmobile/data/database/CommentsDao.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/model/Collector.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/model/Comment.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/CommentRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/ApiClient.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/CommentApi.kt
  app/src/main/java/com/uniandes/vynilsmobile/data/service/RetrofitBroker.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumDetailFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CommentCreateFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/adapters/CommentsAdapter.kt
  app/src/main/java/com/uniandes/vynilsmobile/viewmodel/CommentCreateViewModel.kt
  app/src/main/res/layout/album_detail_fragment.xml
  app/src/main/res/layout/comment_create_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: HU09

#81 [i18n] Primera version i18n para vinilos
  app/src/main/java/com/uniandes/vynilsmobile/data/repository/AlbumRepository.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/AlbumCreateFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/CommentCreateFragment.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/MainActivity.kt
  app/src/main/java/com/uniandes/vynilsmobile/view/PrizeCreateFragment.kt
  app/src/main/res/drawable/ic_flag_es.xml
  app/src/main/res/drawable/ic_flag_us.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_detail_fragment.xml
  app/src/main/res/layout/comment_create_fragment.xml
  app/src/main/res/menu/toolbar_menu.xml
  app/src/main/res/values-en-rUS/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
